setup.kibana.host: "http://kibana:5601"

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

processors:
- add_cloud_metadata: ~

- drop_event:
    when:
        or:
            - contains:
                container.name: "logstash-indexer"
            - contains:
                docker.container.image: "filebeat"
            - contains:
                docker.container.image: "rancher/healthcheck"
            - contains:
                docker.container.image: "rancher/net"
            - contains:
                docker.container.image: "rancher/storage"
            - contains:
                docker.container.image: "rancher/scheduler"
            - contains:
                docker.container.image: "rancher/metadata"
            - contains:
                docker.container.image: "rancher/dns"
            - contains:
                docker.container.image: "rancher/network-manager"
            - contains:
                docker.container.image: "rancher/agent"
            - contains:
                container.labels.io_rancher_project_name: "network-services"
            - contains:
                container.labels.io_rancher_project_name: "ipsec"

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: 'elastic'
  password: 'elastic123PEN'
#output.logstash:
#    hosts: ["logstash:5044"]
